# build an executable named  from encrypt.c
  all: .encrypt.c
 	  gcc -g -Wall -o encrypt encrypt.c

  clean: 
	  $(RM) encrypt
# build an executable named  from Keygen.c
  all: Keygen.c
 	  gcc -g -Wall -o Keygen Keygen.c

  clean: 
	  $(RM) Keygen